name: Pull Request updated

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  history:
    name: Pull Request Body
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.head.ref, 'epic/release')
    steps:
      - name: Pull Request Body
        uses: technote-space/pr-commit-body-action@v1
        with:
          TITLE: ${{ env.PR_BODY_TITLE }}
