# github APIエンドポイントにPOSTすることで発火
# 発火後は空のcommitを追加してPRを作成する
on:
  repository_dispatch:
    types: event_type

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update dependencies
        run: |
          git config --local user.name ssabcire
          git config --local user.email qasw4554@gmail.com
          git commit --allow-empty -m "first commit"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: test
          title: "Epic/release 202006w2"
          branch: epic/release_07
          base: master
          body: |
            # Summary
            This PR is 202006w2 of release branch.
            # PR title and number
          # labels: Weekly Release
