name: create release automatically

on:
  pull_request:
    types: closed
    branches:
      - master

jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.head.ref, 'release/')
    steps:
      - name: get tag
        run: echo ::set-env name=TAG::$(echo ${{ github.event.pull_request.head.ref }} | awk -F'/' '{print $2}')
      - name: print tag
        run: echo ${TAG}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ TAG }}
          release_name: Release ${{ TAG }}
          body: ${{ github.event.pull_request.body }}
          draft: true
          prerelease: false
