name: PR INFO echo

on:
  create

jobs:
  history:
    name: echo json
    runs-on: ubuntu-latest
    steps:
      - name: dump context
        # run: echo '${{ toJSON(github.event) }}'
        run: echo ${{ github.event.ref }}
