name: Create Release PR with cURL github API

on:
  repository_dispatch:
    types: event_type

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - env:
        BRANCH_NAME: release/${{ github.event.client_payload.tag }}

      - uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0

      - name: Make and push release branch
        run: |
          git config --local user.name ssabcire
          git config --local user.email qasw4554@gmail.com
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Create a release PR
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_STAGING: $BRANCH_NAME
        run: |
          gem install -N git-pr-release -v "1.4.0"
          git-pr-release --no-fetch
